### ISSUE TITLE
Allow disabling registrations from config

### ISSUE THREAD

**Issue by msfjarvis** [nulli0n/NexAuth-spigot#4]
My use case for this is to turn off registrations after all the people who are supposed to be signed up have already done so, and use NexAuth as a rudimentary firewall to prevent other players who scrape the IP to be unable to also log onto the server and leverage the open registration to potentially grief the server.

**Comment by nulli0n** [comment]
Just use whitelist then?

**Comment by msfjarvis** [comment]
I... feel stupid. Thanks for the tip!
