### ISSUE TITLE
Conflicting player name when a player with a different name but the same initial characters is already playing in the game

### ISSUE THREAD

**Issue by exwtsaikaimemes** [nulli0n/NexAuth-spigot#9]
On LoginListener.java please update the line 76 with this extra check in the if statement.
This prevents a bug where when a player named "Test123" is already playing and a player named "test" tries to join
The getPlayer function for some reason fuzzy matches Test123 and the duplicate variable is getting populated with the
wrong player name. I would've open a Pull request but I am not allowed to.

```
Player duplicate = plugin.getServer().getPlayer(userName);
if (duplicate != null && duplicate.getName().equalsIgnoreCase(userName)) {
    String msg = plugin.getMessage(Lang.JOIN_ERROR_ALREADY_LOGGED).getLocalized();
    e.disallow(AsyncPlayerPreLoginEvent.Result.KICK_OTHER, msg);
}
```

**Comment by nulli0n** [comment]
Fixed in v2.1.0
